import { FormBlockBase, COMMON_FORM_FIELDS, COMMON_FORM_DEFAULTS } from './_FormBlockBase';

// Event / conference registration — name, contact, role, dietary requirements.
export const FormRegistration = {
  label: 'Registration form',
  fields: COMMON_FORM_FIELDS,
  defaultProps: {
    ...COMMON_FORM_DEFAULTS,
    form_heading: 'Register for the event',
    form_lede: "Secure your spot. We'll email your confirmation and joining instructions.",
    form_submit_label: 'Register now',
    success_heading: "You're registered.",
    success_body: 'Check your inbox for a confirmation email with all the details.',
    fields: [
      { field_type: 'text',  field_key: 'full_name',   label: 'Full name',   placeholder: 'Your name',           required: 'yes', width: 'half', validation: 'none',  options: '', default_value: '', help_text: '' },
      { field_type: 'email', field_key: 'email',       label: 'Email',       placeholder: 'you@company.com',     required: 'yes', width: 'half', validation: 'email', options: '', default_value: '', help_text: '' },
      { field_type: 'tel',   field_key: 'phone',       label: 'Phone',       placeholder: '+1 555 000 0000',     required: 'no',  width: 'half', validation: 'phone', options: '', default_value: '', help_text: 'Optional' },
      { field_type: 'text',  field_key: 'company',     label: 'Organisation',placeholder: 'Your company',        required: 'no',  width: 'half', validation: 'none',  options: '', default_value: '', help_text: 'Optional' },
      {
        field_type: 'select',
        field_key: 'role',
        label: 'Your role',
        placeholder: 'Select your role',
        required: 'no',
        width: 'half',
        validation: 'none',
        options: 'Developer\nDesigner\nProduct manager\nMarketer\nFounder / exec\nStudent\nOther',
        default_value: '',
        help_text: '',
      },
      {
        field_type: 'select',
        field_key: 'tshirt_size',
        label: 'T-shirt size',
        placeholder: 'Select size',
        required: 'no',
        width: 'half',
        validation: 'none',
        options: 'XS\nS\nM\nL\nXL\nXXL',
        default_value: '',
        help_text: 'Optional — if swag is included',
      },
      {
        field_type: 'select',
        field_key: 'dietary',
        label: 'Dietary requirements',
        placeholder: 'Select one',
        required: 'no',
        width: 'full',
        validation: 'none',
        options: 'No restrictions\nVegetarian\nVegan\nGluten-free\nHalal\nKosher\nOther',
        default_value: 'No restrictions',
        help_text: '',
      },
      { field_type: 'textarea', field_key: 'notes', label: 'Additional notes', placeholder: 'Accessibility needs, questions, or anything else…', required: 'no', width: 'full', validation: 'none', options: '', default_value: '', help_text: 'Optional' },
    ],
  },
  render: (props) => <FormBlockBase {...props} />,
};
